-- =============================================================================
--  Klany - rozszerzenia.
--
--  clan_members.chat_read_id   - do ktorej wiadomosci czatu ta osoba przeczytala (licznik
--                                nieprzeczytanych); istniejacym czlonkom ustawiamy ostatnia
--                                wiadomosc klanu, zeby po wdrozeniu nikt nie zobaczyl calej
--                                historii jako "nowej".
--  clan_members.chat_muted     - wyciszone powiadomienia na telefon z czatu klanu.
--  clan_messages.reply_to_id   - odpowiedz na wiadomosc (ON DELETE SET NULL: skasowanie
--                                oryginalu zostawia odpowiedz bez cytatu).
--  clan_message_reactions      - reakcje emoji na wiadomosci; jedna na osobe i wiadomosc.
--  clans.announcement(_at)     - przypiete ogloszenie zarzadu.
--  clans.rules                 - krotkie zasady klanu (widza je tez zaproszeni).
--  clan_tracks, clan_track_votes - "utwor tygodnia": propozycje i glosy.
--  reports.clan_id             - zgloszenie klanu (ON DELETE SET NULL: po rozwiazaniu klanu
--                                zgloszenie zostaje, a dowodem jest migawka w report_evidence).
--
--  Poza ostatnim UPDATE i zamianami ograniczenia CHECK plik powstal maszynowo, tak jak V9:
--  schemat z ddl-auto=create zrzucony pg_dumpem i porownany blok po bloku z V10.
--  Wypuszczonej migracji sie nie edytuje.
-- =============================================================================

ALTER TABLE clan_members ADD COLUMN chat_muted boolean DEFAULT false NOT NULL;
ALTER TABLE clan_members ADD COLUMN chat_read_id bigint;

UPDATE clan_members m
   SET chat_read_id = COALESCE((SELECT MAX(x.id) FROM clan_messages x WHERE x.clan_id = m.clan_id), 0);

ALTER TABLE clans ADD COLUMN announcement character varying(500);
ALTER TABLE clans ADD COLUMN announcement_at timestamp(6) without time zone;
ALTER TABLE clans ADD COLUMN rules character varying(600);

ALTER TABLE clan_messages ADD COLUMN reply_to_id bigint;

ALTER TABLE ONLY clan_messages
    ADD CONSTRAINT fkr4icxpxolj9tovw1hl4l0tae9 FOREIGN KEY (reply_to_id) REFERENCES clan_messages(id) ON DELETE SET NULL;

CREATE TABLE clan_message_reactions (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    message_id bigint NOT NULL,
    user_id bigint NOT NULL,
    type character varying(16) NOT NULL,
    CONSTRAINT clan_message_reactions_type_check CHECK (((type)::text = ANY ((ARRAY['THUMBS_UP'::character varying, 'HEART'::character varying, 'LAUGH'::character varying, 'FIRE'::character varying, 'MUSIC'::character varying, 'WOW'::character varying])::text[])))
);

ALTER TABLE clan_message_reactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clan_message_reactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY clan_message_reactions
    ADD CONSTRAINT clan_message_reactions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY clan_message_reactions
    ADD CONSTRAINT uk_clan_message_reactions_pair UNIQUE (message_id, user_id);

CREATE INDEX idx_clan_message_reactions_user ON clan_message_reactions USING btree (user_id);

ALTER TABLE ONLY clan_message_reactions
    ADD CONSTRAINT fk7gu8bnuokl1me7khb9cojyfo8 FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY clan_message_reactions
    ADD CONSTRAINT fk8udo9oyrskrhejbi402hypyap FOREIGN KEY (message_id) REFERENCES clan_messages(id) ON DELETE CASCADE;

CREATE TABLE clan_tracks (
    week_start date NOT NULL,
    clan_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    proposer_id bigint NOT NULL,
    music_kind character varying(16) NOT NULL,
    music_provider character varying(16) NOT NULL,
    note character varying(200),
    music_external_id character varying(300) NOT NULL,
    music_title character varying(300),
    music_thumbnail_url character varying(500),
    CONSTRAINT clan_tracks_music_kind_check CHECK (((music_kind)::text = ANY ((ARRAY['TRACK'::character varying, 'ALBUM'::character varying, 'ARTIST'::character varying, 'PLAYLIST'::character varying])::text[]))),
    CONSTRAINT clan_tracks_music_provider_check CHECK (((music_provider)::text = ANY ((ARRAY['SPOTIFY'::character varying, 'YOUTUBE'::character varying, 'APPLE_MUSIC'::character varying])::text[])))
);

ALTER TABLE clan_tracks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clan_tracks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY clan_tracks
    ADD CONSTRAINT clan_tracks_pkey PRIMARY KEY (id);

CREATE INDEX idx_clan_tracks_clan_week ON clan_tracks USING btree (clan_id, week_start);

ALTER TABLE ONLY clan_tracks
    ADD CONSTRAINT fklcyao52fv17o6trx3gfjaj31o FOREIGN KEY (proposer_id) REFERENCES users(id);

ALTER TABLE ONLY clan_tracks
    ADD CONSTRAINT fkr5rsfkn0v0yshk4ef38sh9gxb FOREIGN KEY (clan_id) REFERENCES clans(id);

CREATE TABLE clan_track_votes (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    track_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE clan_track_votes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clan_track_votes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY clan_track_votes
    ADD CONSTRAINT clan_track_votes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY clan_track_votes
    ADD CONSTRAINT uk_clan_track_votes_pair UNIQUE (track_id, user_id);

CREATE INDEX idx_clan_track_votes_user ON clan_track_votes USING btree (user_id);

ALTER TABLE ONLY clan_track_votes
    ADD CONSTRAINT fk7xf8ehuflxfrf5qr90osxd9fh FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY clan_track_votes
    ADD CONSTRAINT fktowgjw74rkoax5l11a4ps4fla FOREIGN KEY (track_id) REFERENCES clan_tracks(id) ON DELETE CASCADE;

ALTER TABLE reports ADD COLUMN clan_id bigint;

ALTER TABLE reports DROP CONSTRAINT reports_context_check;
ALTER TABLE reports ADD CONSTRAINT reports_context_check CHECK (((context)::text = ANY ((ARRAY['PROFILE'::character varying, 'POST'::character varying, 'CONVERSATION'::character varying, 'CLAN'::character varying])::text[])));

ALTER TABLE ONLY reports
    ADD CONSTRAINT fkt7rfo2ri3xc00slg8ox9hdx0k FOREIGN KEY (clan_id) REFERENCES clans(id) ON DELETE SET NULL;
