-- =============================================================================
--  Klany - spolecznosc: przegladarka, prosby o dolaczenie, tytuly, ankiety.
--
--  clans.motto / city          - haslo i miasto klanu (widoczne dla kazdego zalogowanego).
--  clans.join_policy           - REQUESTS (mozna prosic o dolaczenie) albo INVITE_ONLY. Istniejace
--                                klany zostaja INVITE_ONLY: do tej pory wchodzilo sie tylko z
--                                zaproszenia i nikt nie zmienil zdania.
--  clans.listed                - czy klan jest w przegladarce klanow. Istniejace klany dostaja
--                                false (nikt sie na przegladarke nie zgodzil); nowe klany maja
--                                domyslnie true - zalozyciel moze to wylaczyc przy zakladaniu.
--  clan_genres                 - do trzech gatunkow, ktore klan podaje o sobie.
--  clan_join_requests          - prosby o dolaczenie (PENDING / DECLINED), jedna na osobe i klan.
--  clan_titles, clan_member_titles - tytuly (role) w klanie: nadawane, brane samemu albo
--                                automatyczne z progu aktywnosci (te nie maja wierszy w
--                                clan_member_titles - licza sie na biezaco).
--  clan_polls, clan_poll_options, clan_poll_votes - ankiety w klanie.
--  notifications_type_check    - dwa nowe rodzaje: CLAN_JOIN_REQUEST, CLAN_REQUEST_ACCEPTED.
--
--  Poza kolumna listed i zamiana ograniczenia CHECK plik powstal maszynowo, tak jak V9 i V11:
--  schemat z ddl-auto=create zrzucony pg_dumpem i porownany blok po bloku z V11.
--  Wypuszczonej migracji sie nie edytuje.
-- =============================================================================

ALTER TABLE clans ADD COLUMN motto character varying(80);
ALTER TABLE clans ADD COLUMN city character varying(60);
ALTER TABLE clans ADD COLUMN join_policy character varying(16) DEFAULT 'INVITE_ONLY' NOT NULL;
ALTER TABLE clans ADD CONSTRAINT clans_join_policy_check CHECK (((join_policy)::text = ANY ((ARRAY['REQUESTS'::character varying, 'INVITE_ONLY'::character varying])::text[])));

-- Istniejace klany: poza przegladarka (false), nowe: w przegladarce (domyslnie true)
ALTER TABLE clans ADD COLUMN listed boolean DEFAULT false NOT NULL;
ALTER TABLE clans ALTER COLUMN listed SET DEFAULT true;

ALTER TABLE notifications DROP CONSTRAINT notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['REACTION'::character varying, 'FRIEND_REQUEST'::character varying, 'FRIEND_ACCEPTED'::character varying, 'REPORT'::character varying, 'REPORT_RESOLVED'::character varying, 'EVENT_REMINDER'::character varying, 'CLAN_INVITE'::character varying, 'CLAN_KICKED'::character varying, 'CLAN_JOIN_REQUEST'::character varying, 'CLAN_REQUEST_ACCEPTED'::character varying])::text[])));

CREATE TABLE clan_genres (
    "position" integer NOT NULL,
    clan_id bigint NOT NULL,
    genre character varying(30)
);

ALTER TABLE ONLY clan_genres
    ADD CONSTRAINT clan_genres_pkey PRIMARY KEY ("position", clan_id);

ALTER TABLE ONLY clan_genres
    ADD CONSTRAINT fkrlofei0fv27pyxoceguumv9wk FOREIGN KEY (clan_id) REFERENCES clans(id);

CREATE TABLE clan_join_requests (
    answered_at timestamp(6) without time zone,
    clan_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    status character varying(16) NOT NULL,
    message character varying(200),
    CONSTRAINT clan_join_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'DECLINED'::character varying])::text[])))
);

ALTER TABLE clan_join_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clan_join_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY clan_join_requests
    ADD CONSTRAINT clan_join_requests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY clan_join_requests
    ADD CONSTRAINT uk_clan_join_requests_pair UNIQUE (clan_id, user_id);

CREATE INDEX idx_clan_join_requests_user ON clan_join_requests USING btree (user_id);

ALTER TABLE ONLY clan_join_requests
    ADD CONSTRAINT fk96bcka92k7i55an1ioxi588ix FOREIGN KEY (clan_id) REFERENCES clans(id);

ALTER TABLE ONLY clan_join_requests
    ADD CONSTRAINT fkal6wxno981av7g1tduor0k6h3 FOREIGN KEY (user_id) REFERENCES users(id);

CREATE TABLE clan_titles (
    threshold integer,
    clan_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    color character varying(16) NOT NULL,
    metric character varying(16),
    mode character varying(16) NOT NULL,
    name character varying(24) NOT NULL,
    name_key character varying(64) NOT NULL,
    CONSTRAINT clan_titles_color_check CHECK (((color)::text = ANY ((ARRAY['VIOLET'::character varying, 'PINK'::character varying, 'RED'::character varying, 'ORANGE'::character varying, 'AMBER'::character varying, 'GREEN'::character varying, 'TEAL'::character varying, 'BLUE'::character varying, 'INDIGO'::character varying, 'SLATE'::character varying])::text[]))),
    CONSTRAINT clan_titles_metric_check CHECK (((metric)::text = ANY ((ARRAY['MESSAGES'::character varying, 'POSTS'::character varying, 'TRACKS'::character varying, 'VOTES'::character varying, 'REACTIONS'::character varying, 'DAYS'::character varying])::text[]))),
    CONSTRAINT clan_titles_mode_check CHECK (((mode)::text = ANY ((ARRAY['MANUAL'::character varying, 'SELF'::character varying, 'AUTO'::character varying])::text[])))
);

ALTER TABLE clan_titles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clan_titles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY clan_titles
    ADD CONSTRAINT clan_titles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY clan_titles
    ADD CONSTRAINT uk_clan_titles_name UNIQUE (clan_id, name_key);

CREATE INDEX idx_clan_titles_clan ON clan_titles USING btree (clan_id);

ALTER TABLE ONLY clan_titles
    ADD CONSTRAINT fknwi32n8g05y1s5rm20ygo821v FOREIGN KEY (clan_id) REFERENCES clans(id);

CREATE TABLE clan_member_titles (
    self_claimed boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    title_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE clan_member_titles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clan_member_titles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY clan_member_titles
    ADD CONSTRAINT clan_member_titles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY clan_member_titles
    ADD CONSTRAINT uk_clan_member_titles_pair UNIQUE (title_id, user_id);

CREATE INDEX idx_clan_member_titles_user ON clan_member_titles USING btree (user_id);

ALTER TABLE ONLY clan_member_titles
    ADD CONSTRAINT fk63g268p3g5s6gsk8httgdr95t FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY clan_member_titles
    ADD CONSTRAINT fkkjb1pkj8j45r6blp42qcai515 FOREIGN KEY (title_id) REFERENCES clan_titles(id) ON DELETE CASCADE;

CREATE TABLE clan_polls (
    closed boolean NOT NULL,
    author_id bigint NOT NULL,
    clan_id bigint NOT NULL,
    closes_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    question character varying(150) NOT NULL
);

ALTER TABLE clan_polls ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clan_polls_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY clan_polls
    ADD CONSTRAINT clan_polls_pkey PRIMARY KEY (id);

CREATE INDEX idx_clan_polls_clan ON clan_polls USING btree (clan_id, id);

ALTER TABLE ONLY clan_polls
    ADD CONSTRAINT fk10w0d4qs511nb5k7o8ounpw9d FOREIGN KEY (author_id) REFERENCES users(id);

ALTER TABLE ONLY clan_polls
    ADD CONSTRAINT fkeshhcguilgd6j56iwk4kjsr68 FOREIGN KEY (clan_id) REFERENCES clans(id);

CREATE TABLE clan_poll_options (
    "position" integer NOT NULL,
    id bigint NOT NULL,
    poll_id bigint NOT NULL,
    text character varying(80) NOT NULL
);

ALTER TABLE clan_poll_options ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clan_poll_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY clan_poll_options
    ADD CONSTRAINT clan_poll_options_pkey PRIMARY KEY (id);

ALTER TABLE ONLY clan_poll_options
    ADD CONSTRAINT fki7j4uind09xdg511fhtokk65i FOREIGN KEY (poll_id) REFERENCES clan_polls(id) ON DELETE CASCADE;

CREATE TABLE clan_poll_votes (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    option_id bigint NOT NULL,
    poll_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE clan_poll_votes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clan_poll_votes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY clan_poll_votes
    ADD CONSTRAINT clan_poll_votes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY clan_poll_votes
    ADD CONSTRAINT uk_clan_poll_votes_pair UNIQUE (poll_id, user_id);

CREATE INDEX idx_clan_poll_votes_option ON clan_poll_votes USING btree (option_id);

CREATE INDEX idx_clan_poll_votes_user ON clan_poll_votes USING btree (user_id);

ALTER TABLE ONLY clan_poll_votes
    ADD CONSTRAINT fk2fvrakyacmx64muu40vvskkek FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY clan_poll_votes
    ADD CONSTRAINT fkbpaoiqvc1o2ahn013l29s5nf2 FOREIGN KEY (poll_id) REFERENCES clan_polls(id) ON DELETE CASCADE;

ALTER TABLE ONLY clan_poll_votes
    ADD CONSTRAINT fke7c00lo46vogul1681ljfe4e FOREIGN KEY (option_id) REFERENCES clan_poll_options(id) ON DELETE CASCADE;
