-- =============================================================================
--  Komentarze pod postami, odpowiedzi i oznaczenia (@login).
--
--  comments            - komentarz pierwszego poziomu (parent_id = NULL) albo odpowiedz pod nim; reply_to_id
--                        to osoba, do ktorej jest odpowiedz. Znika razem z postem, autorem i komentarzem
--                        nadrzednym (ON DELETE CASCADE) - zadna sciezka kasowania postow (konto, klan,
--                        administrator) nie musi o komentarzach pamietac.
--  comment_mentions    - osoby oznaczone w komentarzu (tylko te, ktore dalo sie oznaczyc w chwili pisania).
--  notifications       - comment_id (znika razem z komentarzem) i trzy nowe rodzaje: POST_COMMENT,
--                        COMMENT_REPLY, COMMENT_MENTION.
--  reports             - comment_id (ON DELETE SET NULL: skasowanie komentarza zostawia zgloszenie jako
--                        historie, a tresc jest w migawce dowodow) i kontekst COMMENT.
--
--  Plik powstal maszynowo, tak jak V9 - V13: schemat z ddl-auto=create zrzucony pg_dumpem i porownany
--  blok po bloku z V13. Wypuszczonej migracji sie nie edytuje.
-- =============================================================================

CREATE TABLE comments (
    author_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    parent_id bigint,
    post_id bigint NOT NULL,
    reply_to_id bigint,
    content character varying(1000) NOT NULL
);

ALTER TABLE comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

CREATE INDEX idx_comments_author ON comments USING btree (author_id, created_at);
CREATE INDEX idx_comments_parent ON comments USING btree (parent_id, created_at);
CREATE INDEX idx_comments_post ON comments USING btree (post_id, created_at);

ALTER TABLE ONLY comments
    ADD CONSTRAINT fkh4c7lvsc298whoyd4w9ta25cr FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE;
ALTER TABLE ONLY comments
    ADD CONSTRAINT fkn2na60ukhs76ibtpt9burkm27 FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE ONLY comments
    ADD CONSTRAINT fklri30okf66phtcgbe5pok7cc0 FOREIGN KEY (parent_id) REFERENCES comments(id) ON DELETE CASCADE;
ALTER TABLE ONLY comments
    ADD CONSTRAINT fkidg9fis5dite7i85o24l306q FOREIGN KEY (reply_to_id) REFERENCES users(id) ON DELETE SET NULL;

CREATE TABLE comment_mentions (
    comment_id bigint NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE comment_mentions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME comment_mentions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY comment_mentions
    ADD CONSTRAINT comment_mentions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY comment_mentions
    ADD CONSTRAINT uq_comment_mentions UNIQUE (comment_id, user_id);

CREATE INDEX idx_comment_mentions_user ON comment_mentions USING btree (user_id);

ALTER TABLE ONLY comment_mentions
    ADD CONSTRAINT fk8gk4oq6ekw42dprikm64qc2u2 FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE;
ALTER TABLE ONLY comment_mentions
    ADD CONSTRAINT fkjaxg8hubwrypwhdcla0gi0q8f FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE notifications ADD COLUMN comment_id bigint;
ALTER TABLE ONLY notifications
    ADD CONSTRAINT fkl7p8sj183bxuwg2sq2ltx3cpv FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE;

ALTER TABLE notifications DROP CONSTRAINT notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['REACTION'::character varying, 'FRIEND_REQUEST'::character varying, 'FRIEND_ACCEPTED'::character varying, 'REPORT'::character varying, 'REPORT_RESOLVED'::character varying, 'EVENT_REMINDER'::character varying, 'CLAN_INVITE'::character varying, 'CLAN_KICKED'::character varying, 'CLAN_JOIN_REQUEST'::character varying, 'CLAN_REQUEST_ACCEPTED'::character varying, 'POST_COMMENT'::character varying, 'COMMENT_REPLY'::character varying, 'COMMENT_MENTION'::character varying])::text[])));

ALTER TABLE reports ADD COLUMN comment_id bigint;
ALTER TABLE ONLY reports
    ADD CONSTRAINT fk3x8ylsypiesh2gkwdy5ug7qe7 FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE SET NULL;

ALTER TABLE reports DROP CONSTRAINT reports_context_check;
ALTER TABLE reports ADD CONSTRAINT reports_context_check CHECK (((context)::text = ANY ((ARRAY['PROFILE'::character varying, 'POST'::character varying, 'CONVERSATION'::character varying, 'CLAN'::character varying, 'COMMENT'::character varying])::text[])));
