-- =============================================================================
--  Karta profilu (zdjecia, "o mnie", "szukam", pytania muzyczne) i tryb Poznawaj (karty w stylu Tindera:
--  wzajemne "tak" = znajomosc).
--
--  users.bio                - "o mnie", zwykly tekst.
--  users.looking_for        - "szukam": do trzech nazw z LookingFor oddzielonych przecinkami (konwerter w
--                             aplikacji; bez CHECK, bo to lista, a nie jedna wartosc).
--  users.discover_enabled   - tryb Poznawaj; domyslnie wylaczony - istniejace konta nie trafiaja do niczyjej
--                             talii, dopoki same go nie wlacza.
--  users.discover_radius_km - zasieg talii od miasta z profilu; 0 = caly kraj.
--  profile_photos           - galeria (do 6 zdjec), pierwsze = okladka karty. Pliki leza tam, gdzie zdjecia
--                             postow; aplikacja kasuje je razem z kontem.
--  profile_prompts          - odpowiedzi na pytania muzyczne (do 3, kazde pytanie raz).
--  discover_swipes          - decyzje "tak"/"nie" (jedna na pare). Wzajemne "tak" zamienia sie w znajomosc
--                             i oba wiersze znikaja; "nie" wygasa po 30 dniach, "tak" bez odpowiedzi po 180.
--  notifications            - nowy rodzaj DISCOVER_MATCH (pelna lista w CHECK, jak w V14).
--
--  Plik powstal maszynowo, tak jak V9 - V16: schemat z ddl-auto=create zrzucony pg_dumpem i porownany blok po
--  bloku z V16. Wypuszczonej migracji sie nie edytuje.
-- =============================================================================

ALTER TABLE users ADD COLUMN bio character varying(300);
ALTER TABLE users ADD COLUMN looking_for character varying(200);
ALTER TABLE users ADD COLUMN discover_enabled boolean DEFAULT false NOT NULL;
ALTER TABLE users ADD COLUMN discover_radius_km integer DEFAULT 100 NOT NULL;

CREATE TABLE profile_photos (
    "position" integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    file_name character varying(120) NOT NULL
);

ALTER TABLE profile_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME profile_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY profile_photos
    ADD CONSTRAINT profile_photos_pkey PRIMARY KEY (id);

CREATE INDEX idx_profile_photos_user ON profile_photos USING btree (user_id, "position");

ALTER TABLE ONLY profile_photos
    ADD CONSTRAINT fkpcesdbh1jh3dnvrd7okd5vaso FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

CREATE TABLE profile_prompts (
    "position" integer NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    prompt character varying(30) NOT NULL,
    answer character varying(150) NOT NULL,
    CONSTRAINT profile_prompts_prompt_check CHECK (((prompt)::text = ANY ((ARRAY['FIRST_CONCERT'::character varying, 'LIFE_CHANGING_ALBUM'::character varying, 'DESERT_ISLAND'::character varying, 'DREAM_GIG'::character varying, 'GUILTY_PLEASURE'::character varying, 'ON_REPEAT'::character varying, 'KARAOKE'::character varying, 'PARTY_STARTER'::character varying, 'UNPOPULAR_OPINION'::character varying, 'INSTRUMENT'::character varying, 'MORNING_SONG'::character varying, 'UNDERRATED_ARTIST'::character varying])::text[])))
);

ALTER TABLE profile_prompts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME profile_prompts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY profile_prompts
    ADD CONSTRAINT profile_prompts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY profile_prompts
    ADD CONSTRAINT uq_profile_prompts UNIQUE (user_id, prompt);

ALTER TABLE ONLY profile_prompts
    ADD CONSTRAINT fk93ggf4365act958nek1wln0m4 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

CREATE TABLE discover_swipes (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    swiper_id bigint NOT NULL,
    target_id bigint NOT NULL,
    decision character varying(10) NOT NULL,
    CONSTRAINT discover_swipes_decision_check CHECK (((decision)::text = ANY ((ARRAY['LIKE'::character varying, 'PASS'::character varying])::text[])))
);

ALTER TABLE discover_swipes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME discover_swipes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY discover_swipes
    ADD CONSTRAINT discover_swipes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY discover_swipes
    ADD CONSTRAINT uq_discover_swipes UNIQUE (swiper_id, target_id);

CREATE INDEX idx_discover_swipes_swiper ON discover_swipes USING btree (swiper_id, created_at);
CREATE INDEX idx_discover_swipes_target ON discover_swipes USING btree (target_id, decision);

ALTER TABLE ONLY discover_swipes
    ADD CONSTRAINT fkc712gdcnpqbpm57au44ek4lwh FOREIGN KEY (target_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE ONLY discover_swipes
    ADD CONSTRAINT fksled1m4vjijkh3psnq4rt79x3 FOREIGN KEY (swiper_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE notifications DROP CONSTRAINT notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['REACTION'::character varying, 'FRIEND_REQUEST'::character varying, 'FRIEND_ACCEPTED'::character varying, 'REPORT'::character varying, 'REPORT_RESOLVED'::character varying, 'EVENT_REMINDER'::character varying, 'CLAN_INVITE'::character varying, 'CLAN_KICKED'::character varying, 'CLAN_JOIN_REQUEST'::character varying, 'CLAN_REQUEST_ACCEPTED'::character varying, 'POST_COMMENT'::character varying, 'COMMENT_REPLY'::character varying, 'COMMENT_MENTION'::character varying, 'DISCOVER_MATCH'::character varying])::text[])));
