-- =============================================================================
--  Schemat poczatkowy bazy MusicClub.
--
--  Do tej pory schemat powstawal sam, z ustawienia ddl-auto=update: Hibernate
--  ogladal encje i dopisywal brakujace tabele. Na produkcji to sie nie nadaje -
--  potrafi zmiany nie wykonac (np. nie zwezi kolumny, bo mogloby to uciac dane),
--  a wykonanych nie da sie cofnac ani powtorzyc na innym serwerze.
--
--  Od teraz schemat jest w tym pliku i zmienia sie tylko przez kolejne migracje
--  (V2__..., V3__...). Profil produkcyjny ma ddl-auto=validate, wiec Hibernate
--  juz nic nie tworzy - tylko sprawdza, czy baza zgadza sie z encjami, i nie
--  wstaje, jesli sie rozjechaly.
--
--  Plik powstal maszynowo: aplikacja z ddl-auto=create zbudowala schemat na
--  pustej bazie, a pg_dump zrzucil wynik. Dzieki temu jest identyczny z tym,
--  czego Hibernate oczekuje - inaczej validate nie przepuscilby startu.
--
--  W trybie deweloperskim NIC SIE NIE ZMIENIA: tam dalej dziala ddl-auto=update,
--  a Flyway jest wylaczony (patrz application.properties).
-- =============================================================================

--
--

--
-- Name: account_ips; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE account_ips (
    login_count integer NOT NULL,
    first_seen_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_seen_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    address character varying(45) NOT NULL
);

--
-- Name: account_ips_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE account_ips ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account_ips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: artist_genres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE artist_genres (
    artist_id bigint NOT NULL,
    genre character varying(60)
);

--
-- Name: artists; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE artists (
    id bigint NOT NULL,
    external_id character varying(64) NOT NULL,
    name character varying(200) NOT NULL,
    image_url character varying(500)
);

--
-- Name: artists_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE artists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME artists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: blocked_ips; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE blocked_ips (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    address character varying(45) NOT NULL,
    blocked_by character varying(50) NOT NULL,
    reason character varying(500) NOT NULL
);

--
-- Name: blocked_ips_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE blocked_ips ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME blocked_ips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: favorite_playlists; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE favorite_playlists (
    "position" integer NOT NULL,
    added_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    owner_id bigint NOT NULL,
    provider character varying(16) NOT NULL,
    external_id character varying(300) NOT NULL,
    title character varying(300),
    thumbnail_url character varying(500),
    CONSTRAINT favorite_playlists_provider_check CHECK (((provider)::text = ANY ((ARRAY['SPOTIFY'::character varying, 'YOUTUBE'::character varying, 'APPLE_MUSIC'::character varying])::text[])))
);

--
-- Name: favorite_playlists_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE favorite_playlists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME favorite_playlists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: friend_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE friend_requests (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    recipient_id bigint NOT NULL,
    sender_id bigint NOT NULL
);

--
-- Name: friend_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE friend_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME friend_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE messages (
    hidden_for_recipient boolean DEFAULT false NOT NULL,
    hidden_for_sender boolean DEFAULT false NOT NULL,
    music_start_seconds integer,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    read_at timestamp(6) without time zone,
    recipient_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    music_kind character varying(16),
    music_provider character varying(16),
    music_external_id character varying(300),
    music_title character varying(300),
    music_thumbnail_url character varying(500),
    content text,
    CONSTRAINT messages_music_kind_check CHECK (((music_kind)::text = ANY ((ARRAY['TRACK'::character varying, 'ALBUM'::character varying, 'ARTIST'::character varying, 'PLAYLIST'::character varying])::text[]))),
    CONSTRAINT messages_music_provider_check CHECK (((music_provider)::text = ANY ((ARRAY['SPOTIFY'::character varying, 'YOUTUBE'::character varying, 'APPLE_MUSIC'::character varying])::text[])))
);

--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE notifications (
    actor_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    post_id bigint,
    read_at timestamp(6) without time zone,
    recipient_id bigint NOT NULL,
    reaction_type character varying(16),
    type character varying(32) NOT NULL,
    CONSTRAINT notifications_reaction_type_check CHECK (((reaction_type)::text = ANY ((ARRAY['FIRE'::character varying, 'MID'::character varying, 'MEH'::character varying])::text[]))),
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['REACTION'::character varying, 'FRIEND_REQUEST'::character varying, 'FRIEND_ACCEPTED'::character varying, 'REPORT'::character varying, 'REPORT_RESOLVED'::character varying])::text[])))
);

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: post_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE post_images (
    "position" integer NOT NULL,
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    file_name character varying(120) NOT NULL
);

--
-- Name: post_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE post_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME post_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE posts (
    music_start_seconds integer,
    author_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    music_kind character varying(16),
    music_provider character varying(16),
    visibility character varying(16),
    music_external_id character varying(300),
    music_title character varying(300),
    music_thumbnail_url character varying(500),
    content text NOT NULL,
    CONSTRAINT posts_music_kind_check CHECK (((music_kind)::text = ANY ((ARRAY['TRACK'::character varying, 'ALBUM'::character varying, 'ARTIST'::character varying, 'PLAYLIST'::character varying])::text[]))),
    CONSTRAINT posts_music_provider_check CHECK (((music_provider)::text = ANY ((ARRAY['SPOTIFY'::character varying, 'YOUTUBE'::character varying, 'APPLE_MUSIC'::character varying])::text[]))),
    CONSTRAINT posts_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'FRIENDS'::character varying])::text[])))
);

--
-- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: reactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE reactions (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL,
    type character varying(16) NOT NULL,
    CONSTRAINT reactions_type_check CHECK (((type)::text = ANY ((ARRAY['FIRE'::character varying, 'MID'::character varying, 'MEH'::character varying])::text[])))
);

--
-- Name: reactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE reactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: report_evidence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE report_evidence (
    "position" integer NOT NULL,
    report_id bigint NOT NULL,
    sent_at timestamp(6) without time zone,
    author character varying(50) NOT NULL,
    text text
);

--
-- Name: reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE reports (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    post_id bigint,
    reported_id bigint NOT NULL,
    reporter_id bigint NOT NULL,
    resolved_at timestamp(6) without time zone,
    context character varying(16) NOT NULL,
    status character varying(16) NOT NULL,
    reason character varying(32) NOT NULL,
    resolved_by character varying(50),
    description text,
    resolution_note text,
    CONSTRAINT reports_context_check CHECK (((context)::text = ANY ((ARRAY['PROFILE'::character varying, 'POST'::character varying, 'CONVERSATION'::character varying])::text[]))),
    CONSTRAINT reports_reason_check CHECK (((reason)::text = ANY ((ARRAY['HARASSMENT'::character varying, 'SPAM'::character varying, 'HATE'::character varying, 'INAPPROPRIATE'::character varying, 'IMPERSONATION'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT reports_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'RESOLVED'::character varying, 'DISMISSED'::character varying])::text[])))
);

--
-- Name: reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: tracks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE tracks (
    id bigint NOT NULL,
    artist_external_id character varying(64),
    external_id character varying(64) NOT NULL,
    artist_name character varying(200) NOT NULL,
    title character varying(300) NOT NULL,
    image_url character varying(500)
);

--
-- Name: tracks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE tracks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tracks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: user_favorite_artists; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE user_favorite_artists (
    artist_id bigint NOT NULL,
    user_id bigint NOT NULL
);

--
-- Name: user_favorite_tracks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE user_favorite_tracks (
    track_id bigint NOT NULL,
    user_id bigint NOT NULL
);

--
-- Name: user_friends; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE user_friends (
    friend_id bigint NOT NULL,
    user_id bigint NOT NULL
);

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE users (
    enabled boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_seen_at timestamp(6) without time zone,
    messaging_banned_until timestamp(6) without time zone,
    posting_banned_until timestamp(6) without time zone,
    role character varying(20) NOT NULL,
    username character varying(50) NOT NULL,
    password_hash character varying(100) NOT NULL,
    avatar_file_name character varying(120),
    email character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: account_ips account_ips_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY account_ips
    ADD CONSTRAINT account_ips_pkey PRIMARY KEY (id);

--
-- Name: artists artists_external_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY artists
    ADD CONSTRAINT artists_external_id_key UNIQUE (external_id);

--
-- Name: artists artists_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY artists
    ADD CONSTRAINT artists_pkey PRIMARY KEY (id);

--
-- Name: blocked_ips blocked_ips_address_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY blocked_ips
    ADD CONSTRAINT blocked_ips_address_key UNIQUE (address);

--
-- Name: blocked_ips blocked_ips_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY blocked_ips
    ADD CONSTRAINT blocked_ips_pkey PRIMARY KEY (id);

--
-- Name: favorite_playlists favorite_playlists_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY favorite_playlists
    ADD CONSTRAINT favorite_playlists_pkey PRIMARY KEY (id);

--
-- Name: friend_requests friend_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY friend_requests
    ADD CONSTRAINT friend_requests_pkey PRIMARY KEY (id);

--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);

--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

--
-- Name: post_images post_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY post_images
    ADD CONSTRAINT post_images_pkey PRIMARY KEY (id);

--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);

--
-- Name: reactions reactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY reactions
    ADD CONSTRAINT reactions_pkey PRIMARY KEY (id);

--
-- Name: report_evidence report_evidence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY report_evidence
    ADD CONSTRAINT report_evidence_pkey PRIMARY KEY ("position", report_id);

--
-- Name: reports reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (id);

--
-- Name: tracks tracks_external_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY tracks
    ADD CONSTRAINT tracks_external_id_key UNIQUE (external_id);

--
-- Name: tracks tracks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY tracks
    ADD CONSTRAINT tracks_pkey PRIMARY KEY (id);

--
-- Name: account_ips uk_account_ips_user_address; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY account_ips
    ADD CONSTRAINT uk_account_ips_user_address UNIQUE (user_id, address);

--
-- Name: friend_requests uk_friend_request_para; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY friend_requests
    ADD CONSTRAINT uk_friend_request_para UNIQUE (sender_id, recipient_id);

--
-- Name: reactions uk_reaction_post_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY reactions
    ADD CONSTRAINT uk_reaction_post_user UNIQUE (post_id, user_id);

--
-- Name: favorite_playlists uq_playlist_owner_item; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY favorite_playlists
    ADD CONSTRAINT uq_playlist_owner_item UNIQUE (owner_id, provider, external_id);

--
-- Name: user_favorite_artists user_favorite_artists_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_favorite_artists
    ADD CONSTRAINT user_favorite_artists_pkey PRIMARY KEY (artist_id, user_id);

--
-- Name: user_favorite_tracks user_favorite_tracks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_favorite_tracks
    ADD CONSTRAINT user_favorite_tracks_pkey PRIMARY KEY (track_id, user_id);

--
-- Name: user_friends user_friends_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_friends
    ADD CONSTRAINT user_friends_pkey PRIMARY KEY (friend_id, user_id);

--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY users
    ADD CONSTRAINT users_email_key UNIQUE (email);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY users
    ADD CONSTRAINT users_username_key UNIQUE (username);

--
-- Name: idx_account_ips_address; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_account_ips_address ON account_ips USING btree (address);

--
-- Name: idx_messages_recipient; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_recipient ON messages USING btree (recipient_id, created_at);

--
-- Name: idx_messages_sender; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_messages_sender ON messages USING btree (sender_id, created_at);

--
-- Name: idx_notifications_recipient; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_recipient ON notifications USING btree (recipient_id, created_at);

--
-- Name: idx_playlists_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_playlists_owner ON favorite_playlists USING btree (owner_id, "position");

--
-- Name: idx_reports_reported; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reports_reported ON reports USING btree (reported_id);

--
-- Name: idx_reports_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reports_status ON reports USING btree (status, created_at);

--
-- Name: user_friends fk11y5boh1e7gh60rdqixyetv3x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_friends
    ADD CONSTRAINT fk11y5boh1e7gh60rdqixyetv3x FOREIGN KEY (friend_id) REFERENCES users(id);

--
-- Name: user_favorite_tracks fk1nssj2f783roiokx791lv64t4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_favorite_tracks
    ADD CONSTRAINT fk1nssj2f783roiokx791lv64t4 FOREIGN KEY (user_id) REFERENCES users(id);

--
-- Name: notifications fk4sd9fik0uthbk6d9rsxco4uja; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY notifications
    ADD CONSTRAINT fk4sd9fik0uthbk6d9rsxco4uja FOREIGN KEY (actor_id) REFERENCES users(id);

--
-- Name: messages fk4ui4nnwntodh6wjvck53dbk9m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY messages
    ADD CONSTRAINT fk4ui4nnwntodh6wjvck53dbk9m FOREIGN KEY (sender_id) REFERENCES users(id);

--
-- Name: notifications fk599539lym3mnkbqks0u806eac; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY notifications
    ADD CONSTRAINT fk599539lym3mnkbqks0u806eac FOREIGN KEY (post_id) REFERENCES posts(id);

--
-- Name: posts fk6xvn0811tkyo3nfjk2xvqx6ns; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY posts
    ADD CONSTRAINT fk6xvn0811tkyo3nfjk2xvqx6ns FOREIGN KEY (author_id) REFERENCES users(id);

--
-- Name: favorite_playlists fk9njtif34keidhb13our6f6s0r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY favorite_playlists
    ADD CONSTRAINT fk9njtif34keidhb13our6f6s0r FOREIGN KEY (owner_id) REFERENCES users(id);

--
-- Name: friend_requests fkcchlh48b4347amfvmke793bg7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY friend_requests
    ADD CONSTRAINT fkcchlh48b4347amfvmke793bg7 FOREIGN KEY (sender_id) REFERENCES users(id);

--
-- Name: reports fkd3qiw2om5d2oh5xb7fbdcq225; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY reports
    ADD CONSTRAINT fkd3qiw2om5d2oh5xb7fbdcq225 FOREIGN KEY (reporter_id) REFERENCES users(id);

--
-- Name: reactions fkh8b4h9wybhu8tc5w11e8t3krc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY reactions
    ADD CONSTRAINT fkh8b4h9wybhu8tc5w11e8t3krc FOREIGN KEY (post_id) REFERENCES posts(id);

--
-- Name: messages fkhdkwfnspwb3s60j27vpg0rpg6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY messages
    ADD CONSTRAINT fkhdkwfnspwb3s60j27vpg0rpg6 FOREIGN KEY (recipient_id) REFERENCES users(id);

--
-- Name: user_favorite_artists fkjv479ghq8sn2q0p4qwd3qfu3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_favorite_artists
    ADD CONSTRAINT fkjv479ghq8sn2q0p4qwd3qfu3 FOREIGN KEY (artist_id) REFERENCES artists(id);

--
-- Name: user_friends fkk08ugelrh9cea1oew3hgxryw2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_friends
    ADD CONSTRAINT fkk08ugelrh9cea1oew3hgxryw2 FOREIGN KEY (user_id) REFERENCES users(id);

--
-- Name: user_favorite_artists fkk2jwqoplfu22jmb22o1as5v8i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_favorite_artists
    ADD CONSTRAINT fkk2jwqoplfu22jmb22o1as5v8i FOREIGN KEY (user_id) REFERENCES users(id);

--
-- Name: user_favorite_tracks fkkp43fbpd4nnkboonnc5fkuyy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY user_favorite_tracks
    ADD CONSTRAINT fkkp43fbpd4nnkboonnc5fkuyy FOREIGN KEY (track_id) REFERENCES tracks(id);

--
-- Name: account_ips fklmjy0b2qphem0w6glbfjmcyc7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY account_ips
    ADD CONSTRAINT fklmjy0b2qphem0w6glbfjmcyc7 FOREIGN KEY (user_id) REFERENCES users(id);

--
-- Name: friend_requests fkmofsv4jjyk6flwplaqwigukl8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY friend_requests
    ADD CONSTRAINT fkmofsv4jjyk6flwplaqwigukl8 FOREIGN KEY (recipient_id) REFERENCES users(id);

--
-- Name: reports fkneu1viyp671jjiwukyfv6dsy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY reports
    ADD CONSTRAINT fkneu1viyp671jjiwukyfv6dsy FOREIGN KEY (post_id) REFERENCES posts(id);

--
-- Name: post_images fko1i5va2d8de9mwq727vxh0s05; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY post_images
    ADD CONSTRAINT fko1i5va2d8de9mwq727vxh0s05 FOREIGN KEY (post_id) REFERENCES posts(id);

--
-- Name: reactions fkqmewaibcp5bxtlqxc2cawhuln; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY reactions
    ADD CONSTRAINT fkqmewaibcp5bxtlqxc2cawhuln FOREIGN KEY (user_id) REFERENCES users(id);

--
-- Name: notifications fkqqnsjxlwleyjbxlmm213jaj3f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY notifications
    ADD CONSTRAINT fkqqnsjxlwleyjbxlmm213jaj3f FOREIGN KEY (recipient_id) REFERENCES users(id);

--
-- Name: report_evidence fkrsbr3ooqnvxto8mhixqyi9j8g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY report_evidence
    ADD CONSTRAINT fkrsbr3ooqnvxto8mhixqyi9j8g FOREIGN KEY (report_id) REFERENCES reports(id);

--
-- Name: artist_genres fkrsiygs82pwn6xqk6prce2eana; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY artist_genres
    ADD CONSTRAINT fkrsiygs82pwn6xqk6prce2eana FOREIGN KEY (artist_id) REFERENCES artists(id);

--
-- Name: reports fks5hp3xww9pl0bwblxl3cfwue2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY reports
    ADD CONSTRAINT fks5hp3xww9pl0bwblxl3cfwue2 FOREIGN KEY (reported_id) REFERENCES users(id);

--
--
