-- =============================================================================
--  Spotkania wysylane na czacie (rozmowy i czat klanu): miejsce, opcjonalny punkt na mapie, czas od-do,
--  przypomnienie dla osob, ktore potwierdzily.
--
--  meetings                  - spotkanie rozmowy (partner_id) albo klanu (clan_id; rozwiazanie klanu kasuje je
--                              kaskada). Czasy to chwile (timestamp with time zone) - przypomnienie liczy sie od
--                              chwili, nie od zegara serwera.
--  meeting_attendees         - odpowiedz osoby: GOING / NOT_GOING i kiedy dostala przypomnienie (jedno na osobe).
--  messages.meeting_id,
--  clan_messages.meeting_id  - wiadomosc, ktora niesie spotkanie; usuniecie spotkania zostawia wiadomosc (SET NULL).
--  notifications.meeting_id  - przypomnienie i odwolanie; znikaja razem ze spotkaniem.
--  notifications_type_check  - odtworzony w calosci z MEETING_REMINDER i MEETING_CANCELLED.
--
--  Jak V1 - V19: zgodne ze zrzutem pg_dump schematu z ddl-auto=create (porownane w calosci).
--  Wypuszczonej migracji sie nie edytuje.
-- =============================================================================

CREATE TABLE meetings (
    latitude double precision,
    longitude double precision,
    remind_minutes integer NOT NULL,
    cancelled_at timestamp(6) with time zone,
    clan_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    creator_id bigint NOT NULL,
    ends_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    partner_id bigint,
    remind_at timestamp(6) with time zone,
    starts_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    place character varying(100) NOT NULL,
    note character varying(200)
);

ALTER TABLE meetings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME meetings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY meetings
    ADD CONSTRAINT meetings_pkey PRIMARY KEY (id);

CREATE INDEX idx_meetings_clan ON meetings USING btree (clan_id, updated_at);
CREATE INDEX idx_meetings_creator ON meetings USING btree (creator_id, ends_at);
CREATE INDEX idx_meetings_remind ON meetings USING btree (remind_at);

ALTER TABLE ONLY meetings
    ADD CONSTRAINT fk1tqkcfynlyxsg923fcwe76fv FOREIGN KEY (clan_id) REFERENCES clans(id) ON DELETE CASCADE;
ALTER TABLE ONLY meetings
    ADD CONSTRAINT fk7vd7vogxn8n8dbrdbyybt89ep FOREIGN KEY (partner_id) REFERENCES users(id);
ALTER TABLE ONLY meetings
    ADD CONSTRAINT fkaa1dp9oxlq8sykp2s8xwcshr7 FOREIGN KEY (creator_id) REFERENCES users(id);

CREATE TABLE meeting_attendees (
    id bigint NOT NULL,
    meeting_id bigint NOT NULL,
    reminded_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    status character varying(16) NOT NULL,
    CONSTRAINT meeting_attendees_status_check CHECK (((status)::text = ANY ((ARRAY['GOING'::character varying, 'NOT_GOING'::character varying])::text[])))
);

ALTER TABLE meeting_attendees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME meeting_attendees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY meeting_attendees
    ADD CONSTRAINT meeting_attendees_pkey PRIMARY KEY (id);
ALTER TABLE ONLY meeting_attendees
    ADD CONSTRAINT uk_meeting_attendee UNIQUE (meeting_id, user_id);

ALTER TABLE ONLY meeting_attendees
    ADD CONSTRAINT fk2ok8604933c4xrov05cgtwh0t FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE ONLY meeting_attendees
    ADD CONSTRAINT fkjrrh506w4qj7m1kap6fup86ni FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE;

ALTER TABLE messages ADD COLUMN meeting_id bigint;
ALTER TABLE ONLY messages
    ADD CONSTRAINT fk6ptnsbqgfhbjgferbbjtasvfo FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE SET NULL;

ALTER TABLE clan_messages ADD COLUMN meeting_id bigint;
ALTER TABLE ONLY clan_messages
    ADD CONSTRAINT fkofclfe0htx2vvvjr4nb4q69ig FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE SET NULL;

ALTER TABLE notifications ADD COLUMN meeting_id bigint;
ALTER TABLE ONLY notifications
    ADD CONSTRAINT fkkmav63uxwcq0ae7nbmu312a1u FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE;

ALTER TABLE notifications DROP CONSTRAINT notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['REACTION'::character varying, 'FRIEND_REQUEST'::character varying, 'FRIEND_ACCEPTED'::character varying, 'REPORT'::character varying, 'REPORT_RESOLVED'::character varying, 'EVENT_REMINDER'::character varying, 'CLAN_INVITE'::character varying, 'CLAN_KICKED'::character varying, 'CLAN_JOIN_REQUEST'::character varying, 'CLAN_REQUEST_ACCEPTED'::character varying, 'POST_COMMENT'::character varying, 'COMMENT_REPLY'::character varying, 'COMMENT_MENTION'::character varying, 'DISCOVER_MATCH'::character varying, 'MEETING_REMINDER'::character varying, 'MEETING_CANCELLED'::character varying])::text[])));
