-- =============================================================================
--  "Kim jest" wykonawca i "Od organizatora" na stronie wydarzenia.
--
--  music_events.*     - dane od organizatora z Ticketmastera: wazne uwagi (pleaseNote), organizator, ceny biletow
--                       (najnizsza, najwyzsza, waluta), tylko dla pelnoletnich, start sprzedazy, dostepnosc.
--  performer_links    - linki wykonawcow z importu (strona, Spotify, YouTube...) - jeden zestaw na nazwe (klucz
--                       NameKeys), nie na wydarzenie.
--  artist_profiles    - opis wykonawcy z Last.fm (artist.getInfo) zapamietany na 30 dni, osobno na jezyk. Kolumna
--                       "similar_artists", bo "similar" jest w PostgreSQL slowem zastrzezonym (H2 je przyjmowal).
--
--  Dane o wykonawcach i wydarzeniach - zadnych danych uzytkownikow.
--  Jak V1 - V20: zgodne ze zrzutem pg_dump schematu z ddl-auto=create (porownane w calosci).
--  Wypuszczonej migracji sie nie edytuje.
-- =============================================================================

ALTER TABLE music_events ADD COLUMN age_restricted boolean DEFAULT false NOT NULL;
ALTER TABLE music_events ADD COLUMN price_currency character varying(3);
ALTER TABLE music_events ADD COLUMN price_max double precision;
ALTER TABLE music_events ADD COLUMN price_min double precision;
ALTER TABLE music_events ADD COLUMN sales_start timestamp(6) with time zone;
ALTER TABLE music_events ADD COLUMN promoter character varying(200);
ALTER TABLE music_events ADD COLUMN accessibility character varying(500);
ALTER TABLE music_events ADD COLUMN please_note character varying(1000);

CREATE TABLE performer_links (
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    kind character varying(16) NOT NULL,
    name_key character varying(200) NOT NULL,
    url character varying(500) NOT NULL,
    CONSTRAINT performer_links_kind_check CHECK (((kind)::text = ANY ((ARRAY['HOMEPAGE'::character varying, 'SPOTIFY'::character varying, 'YOUTUBE'::character varying, 'INSTAGRAM'::character varying, 'FACEBOOK'::character varying, 'TIKTOK'::character varying, 'BANDCAMP'::character varying, 'SOUNDCLOUD'::character varying, 'WIKI'::character varying])::text[])))
);

ALTER TABLE performer_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME performer_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY performer_links
    ADD CONSTRAINT performer_links_pkey PRIMARY KEY (id);
ALTER TABLE ONLY performer_links
    ADD CONSTRAINT uk_performer_link UNIQUE (name_key, kind);

CREATE TABLE artist_profiles (
    lang character varying(5) NOT NULL,
    fetched_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    listeners bigint,
    name character varying(200) NOT NULL,
    name_key character varying(200) NOT NULL,
    bio_url character varying(500),
    similar_artists character varying(1000),
    bio character varying(1500)
);

ALTER TABLE artist_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME artist_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY artist_profiles
    ADD CONSTRAINT artist_profiles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY artist_profiles
    ADD CONSTRAINT uk_artist_profile UNIQUE (name_key, lang);
