-- =============================================================================
--  Ekipy na koncert: kilka osob, ktore ida na to samo wydarzenie razem - skad jada, ilu ich moze byc, czat
--  z miejscem zbiorki.
--
--  crews                     - ekipa: wydarzenie (kasowane razem z nim - ON DELETE CASCADE), zakladajacy, nazwa,
--                              opis, limit 2-12, nabor OPEN / APPROVAL, miasto wyjazdu (z kluczem i wspolrzednymi
--                              z listy miast), zamkniety nabor.
--  crew_members              - czlonkowie; (event_id, user_id) unikalne = jedna ekipa na osobe i koncert;
--                              chat_read_id jak w klanie.
--  crew_requests             - prosby o miejsce (nabor za zgoda); odrzucona zostaje z data na tydzien.
--  crew_messages             - czat ekipy: tekst albo spotkanie (meeting_id, SET NULL), usuniete zostaja jako slad.
--  meetings.crew_id          - spotkanie z czatu ekipy; znika razem z ekipa.
--  notifications.crew_id     - prosby, przyjecia, dolaczenia, usuniecia i spotkania ekipy; znikaja razem z nia.
--  notifications_type_check  - odtworzony w calosci z CREW_JOIN_REQUEST, CREW_REQUEST_ACCEPTED,
--                              CREW_MEMBER_JOINED i CREW_KICKED.
--
--  Jak V1 - V21: zgodne ze zrzutem pg_dump schematu z ddl-auto=create (porownane w calosci).
--  Wypuszczonej migracji sie nie edytuje.
-- =============================================================================


CREATE TABLE crews (
    capacity integer NOT NULL,
    closed boolean DEFAULT false NOT NULL,
    departure_lat double precision,
    departure_lon double precision,
    created_at timestamp(6) without time zone NOT NULL,
    event_id bigint NOT NULL,
    founder_id bigint NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    join_policy character varying(16) NOT NULL,
    departure_city character varying(60),
    title character varying(60),
    departure_city_key character varying(100),
    description character varying(300),
    CONSTRAINT crews_join_policy_check CHECK (((join_policy)::text = ANY ((ARRAY['OPEN'::character varying, 'APPROVAL'::character varying])::text[])))
);

ALTER TABLE crews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME crews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE crew_members (
    chat_read_id bigint,
    crew_id bigint NOT NULL,
    event_id bigint NOT NULL,
    id bigint NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    role character varying(16) NOT NULL,
    CONSTRAINT crew_members_role_check CHECK (((role)::text = ANY ((ARRAY['FOUNDER'::character varying, 'MEMBER'::character varying])::text[])))
);

ALTER TABLE crew_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME crew_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE crew_requests (
    created_at timestamp(6) without time zone NOT NULL,
    crew_id bigint NOT NULL,
    declined_at timestamp(6) without time zone,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    message character varying(200)
);

ALTER TABLE crew_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME crew_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE crew_messages (
    created_at timestamp(6) without time zone NOT NULL,
    crew_id bigint NOT NULL,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    meeting_id bigint,
    sender_id bigint NOT NULL,
    content character varying(1000) NOT NULL
);

ALTER TABLE crew_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME crew_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY crews
    ADD CONSTRAINT crews_pkey PRIMARY KEY (id);

ALTER TABLE ONLY crew_members
    ADD CONSTRAINT crew_members_pkey PRIMARY KEY (id);

ALTER TABLE ONLY crew_requests
    ADD CONSTRAINT crew_requests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY crew_messages
    ADD CONSTRAINT crew_messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY crew_members
    ADD CONSTRAINT uk_crew_member_event UNIQUE (event_id, user_id);

ALTER TABLE ONLY crew_requests
    ADD CONSTRAINT uk_crew_request UNIQUE (crew_id, user_id);

CREATE INDEX idx_crews_event ON crews USING btree (event_id);

CREATE INDEX idx_crew_members_crew ON crew_members USING btree (crew_id);

CREATE INDEX idx_crew_members_user ON crew_members USING btree (user_id);

CREATE INDEX idx_crew_messages_crew ON crew_messages USING btree (crew_id, id);

ALTER TABLE meetings ADD COLUMN crew_id bigint;

CREATE INDEX idx_meetings_crew ON meetings USING btree (crew_id, updated_at);

ALTER TABLE notifications ADD COLUMN crew_id bigint;

ALTER TABLE ONLY crew_members
    ADD CONSTRAINT fk4mkqdwgln58prtlamao57fc7d FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY crew_members
    ADD CONSTRAINT fkle3ac3g8q1sjb0kjj2uq7ksyt FOREIGN KEY (crew_id) REFERENCES crews(id) ON DELETE CASCADE;

ALTER TABLE ONLY crew_messages
    ADD CONSTRAINT fk190d8oaf8p6ejboh38kvr4kr4 FOREIGN KEY (sender_id) REFERENCES users(id);

ALTER TABLE ONLY crew_messages
    ADD CONSTRAINT fk6npxenovxson8u7o2l3xyyj5g FOREIGN KEY (crew_id) REFERENCES crews(id) ON DELETE CASCADE;

ALTER TABLE ONLY crew_messages
    ADD CONSTRAINT fko2vr6njiuu2iwxy3roqmqp1od FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE SET NULL;

ALTER TABLE ONLY crew_requests
    ADD CONSTRAINT fkb69vka6kl2u0gs6j1lxi31swl FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY crew_requests
    ADD CONSTRAINT fkdf96j9eu5245sf258m80oubw1 FOREIGN KEY (crew_id) REFERENCES crews(id) ON DELETE CASCADE;

ALTER TABLE ONLY crews
    ADD CONSTRAINT fk5p1xarqfup98rkq4t62i3bmjf FOREIGN KEY (founder_id) REFERENCES users(id);

ALTER TABLE ONLY crews
    ADD CONSTRAINT fkafr4dvxiy0twnbpvd3lekgdf1 FOREIGN KEY (event_id) REFERENCES music_events(id) ON DELETE CASCADE;

ALTER TABLE ONLY meetings
    ADD CONSTRAINT fkbcymsxk6hhdmcprug0j2m2cgq FOREIGN KEY (crew_id) REFERENCES crews(id) ON DELETE CASCADE;

ALTER TABLE ONLY notifications
    ADD CONSTRAINT fk2k6bqfttbhyshsutqtrn0l7hj FOREIGN KEY (crew_id) REFERENCES crews(id) ON DELETE CASCADE;

ALTER TABLE notifications DROP CONSTRAINT notifications_type_check;

ALTER TABLE notifications ADD CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['REACTION'::character varying, 'FRIEND_REQUEST'::character varying, 'FRIEND_ACCEPTED'::character varying, 'REPORT'::character varying, 'REPORT_RESOLVED'::character varying, 'EVENT_REMINDER'::character varying, 'CLAN_INVITE'::character varying, 'CLAN_KICKED'::character varying, 'CLAN_JOIN_REQUEST'::character varying, 'CLAN_REQUEST_ACCEPTED'::character varying, 'POST_COMMENT'::character varying, 'COMMENT_REPLY'::character varying, 'COMMENT_MENTION'::character varying, 'DISCOVER_MATCH'::character varying, 'MEETING_REMINDER'::character varying, 'MEETING_CANCELLED'::character varying, 'CREW_JOIN_REQUEST'::character varying, 'CREW_REQUEST_ACCEPTED'::character varying, 'CREW_MEMBER_JOINED'::character varying, 'CREW_KICKED'::character varying])::text[])));
