-- =============================================================================
--  Wiele zrodel wydarzen: Ticketmaster (glowne), Bandsintown i Songkick (poboczne, z kluczem).
--
--  music_events.source  - kto zalozyl wydarzenie (glowne zrodlo jego danych); istniejace to Ticketmaster.
--                         Wydarzenia ze zrodel pobocznych maja external_id z przedrostkiem ("bandsintown:123").
--  event_sources        - wydarzenie widziane w zrodle pobocznym: do ktorego naszego nalezy (ten sam koncert to
--                         jedna karta) i co o nim mowi - po kazdym imporcie Ticketmastera braki sa uzupelniane z
--                         tych wpisow od nowa. Znika razem z wydarzeniem.
--
--  Dane o wydarzeniach - zadnych danych uzytkownikow.
--  Jak V1 - V22: zgodne ze zrzutem pg_dump schematu z ddl-auto=create (porownane w calosci).
--  Wypuszczonej migracji sie nie edytuje.
-- =============================================================================


ALTER TABLE music_events ADD COLUMN source character varying(16) DEFAULT 'TICKETMASTER'::character varying NOT NULL;

ALTER TABLE music_events ADD CONSTRAINT music_events_source_check CHECK (((source)::text = ANY ((ARRAY['TICKETMASTER'::character varying, 'BANDSINTOWN'::character varying, 'SONGKICK'::character varying])::text[])));

CREATE TABLE event_sources (
    latitude double precision,
    longitude double precision,
    start_time time(6) without time zone,
    event_id bigint NOT NULL,
    id bigint NOT NULL,
    seen_at timestamp(6) without time zone NOT NULL,
    source character varying(16) NOT NULL,
    external_id character varying(100) NOT NULL,
    venue_name character varying(200),
    address character varying(300),
    description character varying(1000),
    image_url character varying(1000),
    performers character varying(1000),
    ticket_url character varying(1000),
    url character varying(1000),
    CONSTRAINT event_sources_source_check CHECK (((source)::text = ANY ((ARRAY['TICKETMASTER'::character varying, 'BANDSINTOWN'::character varying, 'SONGKICK'::character varying])::text[])))
);

ALTER TABLE event_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME event_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY event_sources
    ADD CONSTRAINT event_sources_pkey PRIMARY KEY (id);

ALTER TABLE ONLY event_sources
    ADD CONSTRAINT uk_event_source UNIQUE (source, external_id);

CREATE INDEX idx_event_sources_event ON event_sources USING btree (event_id);

ALTER TABLE ONLY event_sources
    ADD CONSTRAINT fkjb7hfyx3p4u0wj3d8be6r6ds3 FOREIGN KEY (event_id) REFERENCES music_events(id) ON DELETE CASCADE;
