-- =============================================================================
--  Wydarzenia: koncerty pobierane z Ticketmastera.
--
--  music_events           - jedno wydarzenie = jeden termin. Kolejne terminy
--                           tego samego wydarzenia w tym samym miejscu lacza
--                           sie przez series_key.
--  music_event_performers - sklad, w kolejnosci z plakatu (performer_order).
--
--  Tak jak V1, plik powstal maszynowo: aplikacja z ddl-auto=create zbudowala
--  schemat na pustej bazie, pg_dump go zrzucil, a tu zostaly tylko obiekty,
--  ktorych w V1 nie bylo. Poza nimi zrzut zgadzal sie z V1 co do znaku
--  (sprawdzone porownaniem blok po bloku).
--
--  Wypuszczonej migracji sie nie edytuje. Zmiana w tych tabelach to V3.
-- =============================================================================

--
-- music_event_performers; Type: TABLE
--

CREATE TABLE music_event_performers (
    performer_order integer NOT NULL,
    event_id bigint NOT NULL,
    external_id character varying(64),
    name character varying(200) NOT NULL
);

--
-- music_events; Type: TABLE
--

CREATE TABLE music_events (
    latitude double precision,
    longitude double precision,
    start_date date NOT NULL,
    start_time time(6) without time zone,
    id bigint NOT NULL,
    last_seen_at timestamp(6) without time zone NOT NULL,
    status character varying(16) NOT NULL,
    genre character varying(60),
    sub_genre character varying(60),
    external_id character varying(64) NOT NULL,
    venue_external_id character varying(64),
    city character varying(100),
    city_key character varying(100),
    venue_name character varying(200),
    address character varying(300),
    name character varying(300) NOT NULL,
    series_key character varying(400) NOT NULL,
    image_url character varying(1000),
    thumb_url character varying(1000),
    ticket_url character varying(1000),
    description text,
    CONSTRAINT music_events_status_check CHECK (((status)::text = ANY ((ARRAY['SCHEDULED'::character varying, 'CANCELLED'::character varying, 'POSTPONED'::character varying, 'RESCHEDULED'::character varying])::text[])))
);

--
-- music_events_id_seq; Type: SEQUENCE
--

ALTER TABLE music_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME music_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- music_event_performers music_event_performers_pkey; Type: CONSTRAINT
--

ALTER TABLE ONLY music_event_performers
    ADD CONSTRAINT music_event_performers_pkey PRIMARY KEY (performer_order, event_id);

--
-- music_events music_events_external_id_key; Type: CONSTRAINT
--

ALTER TABLE ONLY music_events
    ADD CONSTRAINT music_events_external_id_key UNIQUE (external_id);

--
-- music_events music_events_pkey; Type: CONSTRAINT
--

ALTER TABLE ONLY music_events
    ADD CONSTRAINT music_events_pkey PRIMARY KEY (id);

--
-- idx_music_events_series; Type: INDEX
--

CREATE INDEX idx_music_events_series ON music_events USING btree (series_key, start_date);

--
-- idx_music_events_start; Type: INDEX
--

CREATE INDEX idx_music_events_start ON music_events USING btree (start_date);

--
-- music_event_performers fkpd3yr050hy87gtesyt4eau3k; Type: FK CONSTRAINT
--

ALTER TABLE ONLY music_event_performers
    ADD CONSTRAINT fkpd3yr050hy87gtesyt4eau3k FOREIGN KEY (event_id) REFERENCES music_events(id);
