-- =============================================================================
--  Zapisy na wydarzenia i gatunki wykonawcow.
--
--  event_participations  - kto jest zainteresowany, kto idzie, kto nie chce
--                          byc na liscie uczestnikow. Jeden zapis na osobe
--                          i wydarzenie pilnuje ograniczenie unikalnosci.
--  performer_tags        - gatunki wykonawcow z koncertow, sprawdzone w Last.fm
--  performer_tag_genres    (do dopasowania "Dla ciebie").
--  music_events.withdrawn_at
--                        - wydarzenie zniknelo z Ticketmastera, ale ktos byl
--                          na nie zapisany, wiec nie zostalo skasowane.
--
--  Jak V1 i V2: nowe obiekty sa przepisane ze zrzutu pg_dump schematu, ktory
--  zbudowala aplikacja z ddl-auto=create. Kolumna withdrawn_at dochodzi
--  przez ALTER, bo tabela music_events juz istnieje. Poza tym zrzut zgadza
--  sie z V1 + V2 blok po bloku (sprawdzone porownaniem).
-- =============================================================================

--
-- music_events.withdrawn_at
--

ALTER TABLE music_events ADD COLUMN withdrawn_at timestamp(6) without time zone;

--
-- event_participations; Type: TABLE
--

CREATE TABLE event_participations (
    hidden boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    event_id bigint NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    status character varying(16) NOT NULL,
    CONSTRAINT event_participations_status_check CHECK (((status)::text = ANY ((ARRAY['INTERESTED'::character varying, 'GOING'::character varying])::text[])))
);

--
-- event_participations_id_seq; Type: SEQUENCE
--

ALTER TABLE event_participations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME event_participations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- performer_tag_genres; Type: TABLE
--

CREATE TABLE performer_tag_genres (
    genre character varying(60),
    name_key character varying(200) NOT NULL
);

--
-- performer_tags; Type: TABLE
--

CREATE TABLE performer_tags (
    checked_at timestamp(6) without time zone NOT NULL,
    name character varying(200) NOT NULL,
    name_key character varying(200) NOT NULL
);

--
-- event_participations event_participations_pkey; Type: CONSTRAINT
--

ALTER TABLE ONLY event_participations
    ADD CONSTRAINT event_participations_pkey PRIMARY KEY (id);

--
-- performer_tags performer_tags_pkey; Type: CONSTRAINT
--

ALTER TABLE ONLY performer_tags
    ADD CONSTRAINT performer_tags_pkey PRIMARY KEY (name_key);

--
-- event_participations uk_event_participations_event_user; Type: CONSTRAINT
--

ALTER TABLE ONLY event_participations
    ADD CONSTRAINT uk_event_participations_event_user UNIQUE (event_id, user_id);

--
-- idx_event_participations_user; Type: INDEX
--

CREATE INDEX idx_event_participations_user ON event_participations USING btree (user_id);

--
-- event_participations fk4oi2ae8wq2rygr2uei24wa69m; Type: FK CONSTRAINT
--

ALTER TABLE ONLY event_participations
    ADD CONSTRAINT fk4oi2ae8wq2rygr2uei24wa69m FOREIGN KEY (user_id) REFERENCES users(id);

--
-- performer_tag_genres fk4rnhc6nw1khxg1me47di7sk9l; Type: FK CONSTRAINT
--

ALTER TABLE ONLY performer_tag_genres
    ADD CONSTRAINT fk4rnhc6nw1khxg1me47di7sk9l FOREIGN KEY (name_key) REFERENCES performer_tags(name_key);

--
-- event_participations fkj6rjj7kfpb4eq8ubq8le8ch6p; Type: FK CONSTRAINT
--

ALTER TABLE ONLY event_participations
    ADD CONSTRAINT fkj6rjj7kfpb4eq8ubq8le8ch6p FOREIGN KEY (event_id) REFERENCES music_events(id);
