-- =============================================================================
--  Kraj wydarzen, potwierdzanie adresow e-mail, uzupelnianie gatunkow.
--
--  music_events.country_code  - kraj wydarzenia (import obejmuje juz nie tylko
--                               Polske). Dotychczasowe wydarzenia sa z Polski.
--  users.events_country       - kraj wybrany w zakladce Wydarzenia; pusty = PL.
--  users.email_verified_at    - kiedy adres potwierdzono linkiem z wiadomosci.
--                               Konta zalozone przed ta migracja dostaja date
--                               zalozenia konta - inaczej po wlaczeniu poczty
--                               nikt dotychczasowy nie moglby sie zalogowac.
--  users.pending_email        - nowy adres czekajacy na klikniecie w link.
--  artists.genres_checked_at  - kiedy Last.fm ostatnio pytano o gatunki
--                               wykonawcy (zeby nie pytac w kolko o tych,
--                               ktorych Last.fm nie zna).
--  email_tokens               - wyslane linki; w bazie tylko skrot SHA-256.
--
--  Jak V1-V3: nowe obiekty sa przepisane ze zrzutu pg_dump schematu, ktory
--  zbudowala aplikacja z ddl-auto=create; kolumny w istniejacych tabelach
--  dochodza przez ALTER. Poza tym zrzut zgadza sie z V1-V3 blok po bloku
--  (sprawdzone porownaniem).
-- =============================================================================

--
-- music_events.country_code
--

ALTER TABLE music_events ADD COLUMN country_code character varying(2);

UPDATE music_events SET country_code = 'PL';

CREATE INDEX idx_music_events_country_start ON music_events USING btree (country_code, start_date);

--
-- users: kraj wydarzen i potwierdzanie adresu
--

ALTER TABLE users ADD COLUMN events_country character varying(2);
ALTER TABLE users ADD COLUMN email_verified_at timestamp(6) without time zone;
ALTER TABLE users ADD COLUMN pending_email character varying(255);

UPDATE users SET email_verified_at = created_at;

--
-- artists.genres_checked_at
--

ALTER TABLE artists ADD COLUMN genres_checked_at timestamp(6) without time zone;

--
-- email_tokens; Type: TABLE
--

CREATE TABLE email_tokens (
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token_hash character varying(64) NOT NULL,
    email character varying(255) NOT NULL
);

ALTER TABLE email_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME email_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY email_tokens
    ADD CONSTRAINT email_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY email_tokens
    ADD CONSTRAINT email_tokens_token_hash_key UNIQUE (token_hash);

CREATE INDEX idx_email_tokens_user_created ON email_tokens USING btree (user_id, created_at);

ALTER TABLE ONLY email_tokens
    ADD CONSTRAINT fk9j2pq9xa8fh246k3uruj9feec FOREIGN KEY (user_id) REFERENCES users(id);
