-- =============================================================================
--  Blokowanie uzytkownikow i ustawienia prywatnosci.
--
--  user_blocks                  - kto kogo zablokowal (dziala w obie strony:
--                                 posty, profil, zaproszenia, propozycje).
--  users.profile_visibility     - szczegoly profilu dla wszystkich / znajomych.
--  users.friend_requests_from   - kto moze zaprosic: kazdy / znajomi znajomych / nikt.
--  users.show_online            - czy inni widza aktywnosc.
--  users.show_in_suggestions    - czy pojawiam sie w propozycjach znajomych.
--  users.hide_on_attendee_lists - domyslne "nie pokazuj mnie" przy nowym zapisie
--                                 na wydarzenie.
--  Wartosci domyslne = zachowanie sprzed tej migracji.
--
--  Jak V1-V5: zgodne ze zrzutem pg_dump schematu z ddl-auto=create
--  (sprawdzone porownaniem blok po bloku).
-- =============================================================================

ALTER TABLE users ADD COLUMN hide_on_attendee_lists boolean DEFAULT false NOT NULL;
ALTER TABLE users ADD COLUMN show_in_suggestions boolean DEFAULT true NOT NULL;
ALTER TABLE users ADD COLUMN show_online boolean DEFAULT true NOT NULL;
ALTER TABLE users ADD COLUMN friend_requests_from character varying(20) DEFAULT 'EVERYONE'::character varying NOT NULL;
ALTER TABLE users ADD COLUMN profile_visibility character varying(20) DEFAULT 'EVERYONE'::character varying NOT NULL;

ALTER TABLE users ADD CONSTRAINT users_friend_requests_from_check
    CHECK (((friend_requests_from)::text = ANY ((ARRAY['EVERYONE'::character varying, 'FRIENDS_OF_FRIENDS'::character varying, 'NOBODY'::character varying])::text[])));
ALTER TABLE users ADD CONSTRAINT users_profile_visibility_check
    CHECK (((profile_visibility)::text = ANY ((ARRAY['EVERYONE'::character varying, 'FRIENDS'::character varying])::text[])));

CREATE TABLE user_blocks (
    blocked_id bigint NOT NULL,
    blocker_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL
);

ALTER TABLE user_blocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_blocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY user_blocks
    ADD CONSTRAINT uk_user_blocks_pair UNIQUE (blocker_id, blocked_id);

ALTER TABLE ONLY user_blocks
    ADD CONSTRAINT user_blocks_pkey PRIMARY KEY (id);

CREATE INDEX idx_user_blocks_blocked ON user_blocks USING btree (blocked_id);

ALTER TABLE ONLY user_blocks
    ADD CONSTRAINT fk7k3mfgb03bnmwh81vqb1u5h80 FOREIGN KEY (blocked_id) REFERENCES users(id);

ALTER TABLE ONLY user_blocks
    ADD CONSTRAINT fkgvu85oyjrfafwttb7iphgmm0v FOREIGN KEY (blocker_id) REFERENCES users(id);
