-- =============================================================================
--  Przypomnienia o wydarzeniach i powiadomienia push.
--
--  push_subscriptions              - urzadzenia (przegladarki) z wlaczonym push;
--                                    stamp = znacznik bezpieczenstwa konta z chwili
--                                    zapisu (po "wyloguj wszedzie" urzadzenie milknie).
--  users.event_reminders           - czy przypominac o wydarzeniach (domyslnie tak).
--  event_participations.reminded_days - ostatni zaliczony prog przypomnienia.
--  notifications.event_id/days_left   - przypomnienie o wydarzeniu; znika razem
--                                    z wydarzeniem (ON DELETE CASCADE).
--  notifications.actor_id          - moze byc pusty: przypomnienie pisze aplikacja.
-- =============================================================================

ALTER TABLE users ADD COLUMN event_reminders boolean DEFAULT true NOT NULL;

ALTER TABLE event_participations ADD COLUMN reminded_days integer;

ALTER TABLE notifications ALTER COLUMN actor_id DROP NOT NULL;
ALTER TABLE notifications ADD COLUMN days_left integer;
ALTER TABLE notifications ADD COLUMN event_id bigint;

ALTER TABLE notifications DROP CONSTRAINT notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['REACTION'::character varying, 'FRIEND_REQUEST'::character varying, 'FRIEND_ACCEPTED'::character varying, 'REPORT'::character varying, 'REPORT_RESOLVED'::character varying, 'EVENT_REMINDER'::character varying])::text[])));

ALTER TABLE ONLY notifications
    ADD CONSTRAINT fkjiy5yoeffysuue98y991x3qpy FOREIGN KEY (event_id) REFERENCES music_events(id) ON DELETE CASCADE;

CREATE TABLE push_subscriptions (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    lang character varying(8) NOT NULL,
    user_id bigint NOT NULL,
    stamp character varying(32) NOT NULL,
    auth character varying(40) NOT NULL,
    p256dh character varying(100) NOT NULL,
    endpoint character varying(1000) NOT NULL
);

ALTER TABLE push_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME push_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY push_subscriptions
    ADD CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY push_subscriptions
    ADD CONSTRAINT uk_push_subscriptions_endpoint UNIQUE (endpoint);

CREATE INDEX idx_push_subscriptions_user ON push_subscriptions USING btree (user_id);

ALTER TABLE ONLY push_subscriptions
    ADD CONSTRAINT fk1v577hpc7v9mdrm2uyk6kqgnl FOREIGN KEY (user_id) REFERENCES users(id);
