-- =============================================================================
--  Klany.
--
--  clans               - klan; kolor to wynik glosowania czlonkow (przeliczany przez aplikacje).
--  clan_members        - czlonkostwo; unikalny user_id = jeden klan na osobe.
--  clan_invitations    - zaproszenia (jedyna droga do klanu); DECLINED zostaje, zeby nie zapraszac
--                        w kolko osoby, ktora odmowila.
--  clan_messages       - czat klanu.
--  posts.clan_id       - post klanu (widoczny tylko dla czlonkow, nie ma go na tablicy).
--  notifications       - zaproszenie do klanu i wyrzucenie (clan_id znika razem z klanem).
--  users.clan_invites_from - kto moze mnie zaprosic do klanu (domyslnie kazdy).
-- =============================================================================

ALTER TABLE users ADD COLUMN clan_invites_from character varying(20) DEFAULT 'EVERYONE'::character varying NOT NULL;
ALTER TABLE users ADD CONSTRAINT users_clan_invites_from_check CHECK (((clan_invites_from)::text = ANY ((ARRAY['EVERYONE'::character varying, 'FRIENDS'::character varying, 'NOBODY'::character varying])::text[])));

CREATE TABLE clans (
    tag character varying(5) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    color character varying(16) NOT NULL,
    name character varying(32) NOT NULL,
    name_key character varying(64) NOT NULL,
    icon_file_name character varying(100),
    photo_file_name character varying(100),
    description character varying(300),
    CONSTRAINT clans_color_check CHECK (((color)::text = ANY ((ARRAY['VIOLET'::character varying, 'PINK'::character varying, 'RED'::character varying, 'ORANGE'::character varying, 'AMBER'::character varying, 'GREEN'::character varying, 'TEAL'::character varying, 'BLUE'::character varying, 'INDIGO'::character varying, 'SLATE'::character varying])::text[])))
);

ALTER TABLE clans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY clans
    ADD CONSTRAINT clans_pkey PRIMARY KEY (id);

ALTER TABLE ONLY clans
    ADD CONSTRAINT uk_clans_name_key UNIQUE (name_key);

ALTER TABLE ONLY clans
    ADD CONSTRAINT uk_clans_tag UNIQUE (tag);

CREATE TABLE clan_members (
    clan_id bigint NOT NULL,
    color_voted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    color_vote character varying(16),
    role character varying(16) NOT NULL,
    CONSTRAINT clan_members_color_vote_check CHECK (((color_vote)::text = ANY ((ARRAY['VIOLET'::character varying, 'PINK'::character varying, 'RED'::character varying, 'ORANGE'::character varying, 'AMBER'::character varying, 'GREEN'::character varying, 'TEAL'::character varying, 'BLUE'::character varying, 'INDIGO'::character varying, 'SLATE'::character varying])::text[]))),
    CONSTRAINT clan_members_role_check CHECK (((role)::text = ANY ((ARRAY['FOUNDER'::character varying, 'ADMIN'::character varying, 'MEMBER'::character varying])::text[])))
);

ALTER TABLE clan_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clan_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY clan_members
    ADD CONSTRAINT clan_members_pkey PRIMARY KEY (id);

ALTER TABLE ONLY clan_members
    ADD CONSTRAINT uk_clan_members_user UNIQUE (user_id);

CREATE INDEX idx_clan_members_clan ON clan_members USING btree (clan_id);

ALTER TABLE ONLY clan_members
    ADD CONSTRAINT fk673u1qu22ihd42jp182lrob68 FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY clan_members
    ADD CONSTRAINT fkm7ksy8y1fkliok0g5n90bvgl9 FOREIGN KEY (clan_id) REFERENCES clans(id);

CREATE TABLE clan_invitations (
    answered_at timestamp(6) without time zone,
    clan_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    invitee_id bigint NOT NULL,
    inviter_id bigint NOT NULL,
    status character varying(16) NOT NULL,
    CONSTRAINT clan_invitations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'DECLINED'::character varying])::text[])))
);

ALTER TABLE clan_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clan_invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY clan_invitations
    ADD CONSTRAINT clan_invitations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY clan_invitations
    ADD CONSTRAINT uk_clan_invitations_pair UNIQUE (clan_id, invitee_id);

CREATE INDEX idx_clan_invitations_invitee ON clan_invitations USING btree (invitee_id);

ALTER TABLE ONLY clan_invitations
    ADD CONSTRAINT fk6jdm0d7ba2960hfemhjxsbvlw FOREIGN KEY (clan_id) REFERENCES clans(id);

ALTER TABLE ONLY clan_invitations
    ADD CONSTRAINT fk79wb7fbacm1j5o06888ga4w97 FOREIGN KEY (inviter_id) REFERENCES users(id);

ALTER TABLE ONLY clan_invitations
    ADD CONSTRAINT fk9c69kf58lool933fwpx6fy941 FOREIGN KEY (invitee_id) REFERENCES users(id);

CREATE TABLE clan_messages (
    clan_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    sender_id bigint NOT NULL,
    content character varying(1000) NOT NULL
);

ALTER TABLE clan_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clan_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY clan_messages
    ADD CONSTRAINT clan_messages_pkey PRIMARY KEY (id);

CREATE INDEX idx_clan_messages_clan ON clan_messages USING btree (clan_id, id);

ALTER TABLE ONLY clan_messages
    ADD CONSTRAINT fkcwgpkf39iop0fmui0ni8yg3rs FOREIGN KEY (clan_id) REFERENCES clans(id);

ALTER TABLE ONLY clan_messages
    ADD CONSTRAINT fkff9gwtm1dw63srxftatrrixwt FOREIGN KEY (sender_id) REFERENCES users(id);

ALTER TABLE posts ADD COLUMN clan_id bigint;

CREATE INDEX idx_posts_clan ON posts USING btree (clan_id);

ALTER TABLE ONLY posts
    ADD CONSTRAINT fkhahr0xs16xsfbapdafiqwosug FOREIGN KEY (clan_id) REFERENCES clans(id);

ALTER TABLE notifications ADD COLUMN clan_id bigint;

ALTER TABLE notifications DROP CONSTRAINT notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['REACTION'::character varying, 'FRIEND_REQUEST'::character varying, 'FRIEND_ACCEPTED'::character varying, 'REPORT'::character varying, 'REPORT_RESOLVED'::character varying, 'EVENT_REMINDER'::character varying, 'CLAN_INVITE'::character varying, 'CLAN_KICKED'::character varying])::text[])));

ALTER TABLE ONLY notifications
    ADD CONSTRAINT fk8vuo921ijy33vh80kdda99di9 FOREIGN KEY (clan_id) REFERENCES clans(id) ON DELETE CASCADE;
